### ISSUE TITLE
Determine schema to document valid resource values

### ISSUE THREAD

**Issue by uwe-salomon** [ARINC-IA/CSMIM#6]
The CSMIM standard defines a few limited ways to specify valid resource values (respectively request payloads):

- The `enum-values` spec for resources of type enum
- The `parameters` spec for executable resources

For many resource types, additional definitions would be helpful:

- Unit of measurement for numerical resources
- Allowed value range for numerical resources
- Allowed size of arrays
- Dictionary entries, each with key and type and additional definitions as needed

In essence, this is equivalent or similar to a schema, like [JSON schema](https://json-schema.org/).

This issue is to discuss the need for and merits of such a schema for CSMIM resource values, and potential implementations in our object type YAML files.

**Comment by uwe-salomon** [comment]
After a quick review of [JSON schema](https://json-schema.org), it turns out that this is similar but there are incompatibilities:

- Types for JSON schema are different from CSMIM types
- In particular, CSMIM defines the type of array items already for the array type, while JSON schema 
- Content for `parameters` is structurally different from the `properties` that JSON schema uses for JSON objects = CSMIM dicts
- There is no equivalent to `enum-values` in JSON schema
- `optional` attribute per dict key is structurally different from `required` list of properties per JSON object

Several options here. If we wanted to adopt something close to JSON schema, we could change the structure of the parameters:

```yaml
resources:
  - id: claim
    mode: x
    type: void
    parameters:
      etag:
        type: bytes
      types:
        type: array
        items:
          type: dict
          properties:
            id:
              type: string
            supertypes: 
              type: array
```

and so on. Or we could switch to JSON schema for the definition of the individual parameters:

```yaml
resources:
  - id: claim
    mode: x
    type: void
    parameters:
      - id: etag
        type: bytes
      - id: types
        type: dict[]
        items:
          type: dict
          properties:
            id:
              type: string
            supertypes: 
              type: array
```

**Comment by uwe-salomon** [comment]
Another option is to do something superficially similar to JSON schema, but continue with our existing structure:

```yaml
resources:
  - id: claim
    mode: x
    type: void
    parameters:
      - key: etag
        type: bytes
      - key: types
        type: dict[]
        array-items:
          type: dict
          dict-items:
            - key: id
              type: string
            - key: supertypes
              type: string[]
            - key: resources
              type: dict[]
              array-items:
                type: dict
                dict-items:
                  - key: id
                    type: string
                  - key: type
                    type: string
                  - key: mode
                    type: string
                  - key: optional
                    type: bool
                    optional: true
                  - key: racc
                    type: bool
                    optional: true
```

The `type` of the `array-items` doubles with the type of the array itself, that could be compressed or left as-is.

**Comment by uwe-salomon** [comment]
Another existing schema definion is [RFC 8610](https://datatracker.ietf.org/doc/html/rfc8610), the Concise Data Definition Language. The CDDL can describe arbitrary CBOR payloads, and seems very powerful. The above fragments might look as follows:

```yaml
resources:
  - id: claim
    mode: x
    type: void
    parameters-cddl: |
      parameters = {
        etag: bstr,
        types: [* ObjectType],
      }
      ObjectType = {
        id: tstr,
        supertypes: [* tstr],
        ? racc: boolean,
        resources: [* ResourceType],
      }
      ResourceType = {
        id: tstr,
        type: tstr,
        mode: tstr,
        ? optional: bool,
        ? racc: bool,
      }
```

The `type` and `mode` entries of `ResourceType` could be defined in even more detail, capturing their enumeration character. Descriptions could be embedded as comments. On the other hand, there appears to be no way to specify e.g. the unit of a numeric value formally.

**Comment by ravishankar-hcltech** [comment]
Thanks, Uwe, for outlining various suggestions and providing detailed examples. Following our previous tagups, I’ve spent additional time reviewing options to define a schema for resource values that aligns closely with the underlying wire protocol (CBOR encoding scheme). My focus has been on finding a solution that minimally changes our existing YAML structure while expanding its expressiveness and maintaining both human readability and machine processability.

While JSON Schema offers some useful constructs, I believe we can adopt a hybrid approach that builds on our current YAML/JSON structure while leveraging Concise Data Definition Language (CDDL) as defined in [RFC 8610](https://www.rfc-editor.org/rfc/rfc8610.html). CDDL would be used selectively for defining ranges, enumerations, array sizes, and other constraints, allowing us to enhance expressiveness without requiring a complete overhaul of the schema. This approach aligns well with the goals of CSMIM and leverages existing tooling for validation.

Below, I’ve outlined my proposal along with examples to illustrate how this hybrid approach could work in practice. 

Let me know your thoughts!

## Key Objectives

The key objectives of this proposal are to enhance expressiveness with minimal disruption:

1.  **Expand Expressiveness:** Define units of measurement, value ranges, array sizes, and dictionaries with detailed key-value constraints.
2.  **Maintain Compatibility:** Ensure schema remains human-readable, machine-processable, and compatible with CBOR and JSON.
3.  **Leverage Tooling:** Benefit from existing CDDL tooling (e.g., [cddl-cat](https://github.com/hjson/cddl-cat)) to validate schemas and perform dynamic type checking.

## Proposed Enhancements

Here are the specific enhancements I propose to achieve greater expressiveness while keeping changes minimal:

### 1. Introduce New Elements in YAML

*   **Units of Measurement:** Add a `unit` field for numerical resources (e.g., `unit: ms`).
*   **Range Field:** Use a `range` field to define value ranges, enumerations, or array sizes.
*   **Optionality:** Introduce an `optional` field to explicitly mark elements as optional.

Example YAML:
  
  ```yaml
  resources:
    - id: fadeDuration
      type: uint
      range: "(0..60000)"
      description: Duration of the fade in milliseconds
      unit: ms
      optional: true
  ```
### 2. Expressiveness via CDDL Syntax

The `range` field can leverage CDDL syntax to represent:

*   **Enumerations** (e.g., `&(red: 1, green: 2)`).
*   **Numeric ranges** (e.g., `(0..65535)`).
*   **Array sizes** using occurrence counts (e.g., `[1*4]` for arrays with 1–4 elements).
*   **Complex types** like dictionaries or nested arrays.
  
  Example YAML:
  
  ```yaml
  resources:
    - id: colorCmd
      mode: w
      type: uint[]
      range: "[1*4 (0..65535)]" # Array with 1–4 elements, each in range 0–65535.
      description: Command color in CIELUV 1976 color space
    - id: colorsTest
      mode: w
      type: enum
      range: "&(black: 0, red: 1, green: 2, yellow: 3, blue: 4, magenta: 5, cyan: 6, white: 7)"
      description: Sample enum resource
  ```


### 3. Complex Type Definitions

*   Use CDDL to define complex types such as dictionaries (`map`) or nested arrays.
*   These can be documented inline or referenced in YAML.
  
Example YAML:
  
  ```yaml
  - id: schedCmd
    mode: x
    type: void
    description: Schedule fades for individual sub-units
    parameters:
      - key: c
        type: uint[][]
        range: "[+ [+ uint]]" # Defines a 2D uint array
        description: Colors for each sub-unit
        unit: "-"
  ```


  CDDL Example for Complex Types (Parameters):
  
  ```cddl
  parameters = {
    etag: bstr,
    types: [* ObjectType],
  }
  ObjectType = {
    id: tstr,
    supertypes: [* tstr],
    ? racc: bool,
  }
  ```

### 4. Tooling Benefits:
*   Adopting CDDL enables validation for both JSON and CBOR formats using existing tools (e.g., [cddl](https://www.rfc-editor.org/rfc/rfc8610.html#appendix-F), [CDDL Validator](https://cddl.one/)).
*   This ensures compliance with the schema and facilitates debugging.
  
## Complete Example (csmim.obj.light)

**Input:** YAML Schema

```yaml
---
id: csmim.obj.light.col.1
supertypes: []
description:
  A colored light unit that can consist of sub-units; Register at path
  crew/lights/units/<sec>/<nr>
deprecated: false
attributes:
  - key: sec
    description: Section number in light database
  - key: nr
    description: Consecutive unit number in section
  - key: subs
    description: Number of sub-units
    optional: false
resources:
  - id: colorCmd
    mode: w
    type: uint[]
    range: "[1*4 (0..65535)]" # Defines an array with a min of 1 to 4 elements, each containing a value within 0 to 65535.
    description: Command color in CIELUV 1976 color space [0..65535] for all sub-units
    attributes:
      - key: resattrib-test1
        description: sample resource attribute
  - id: schedCmd
    mode: x
    type: void
    description: Schedule fades for individual sub-units
    parameters:
      - key: c
        type: uint[][]
        range: "[+ [+ uint]]" # Defines a 2D uint array
        description: Colors for each sub-unit
        unit: "-"
      - key: t
        type: utc
        range: utc # Defines an utc type that is defined as either #6.1(int) or #6.1(float) per ARINC853 spec.
        description: Start time of color fade
        unit: time
      - key: d
        type: uint
        range: "(0..60000)"
        description: Fade duration
        unit: ms # Added unit for explicit reference
        optional: true
  - id: colorsTest
    mode: w
    type: enum
    range: "&( black: 0,  red: 1,  green: 2,  yellow: 3, blue: 4,  magenta: 5,  cyan: 6,  white: 7)" # An example to capture the enumerations.
    description: Sample enum resource

```

Equivalent CDDL Schema Representation

```cddl
schema-csmim.obj.light = {
  id: "csmim.obj.light.col.1",
  supertypes: [
  ],
  deprecated: false,
  resources: [
    {
      id: "colorCmd",
      mode: "w",
      type: [1*4 (0..65535)],
      resattrib-test1: tstr
    },
    {
      id: "schedCmd",
      mode: "x",
      type: void,
      parameters: {
        c: [+ [+ uint]],
        t: utc,
        ? d: (0..60000)
      }
    },
    {
      id: "colorsTest",
      mode: "w",
      type: &( black: 0,  red: 1,  green: 2,  yellow: 3, blue: 4,  magenta: 5,  cyan: 6,  white: 7)
    }
  ],
  sec: tstr,
  nr: tstr,
  subs: tstr
}
                   
```

Sample Data Validation Output (CBOR Diagnostic):

```sh
$ ./zValidateData.sh -o csmim.obj.light -f cbor-diag
Starting validation for csmim.obj.light in cbor-diag format
Validating CBOR-Diagnostic format...
[INFO] Root type for validation: schema-csmim.obj.light
[ERROR] Validation from stdin failed:
error validating at cbor location /"supertypes": expected empty array, got Array([Integer(Integer(2))])
Validation complete

$ ./zValidateData.sh -o csmim.obj.light -f cbor-diag
Starting validation for csmim.obj.light in cbor-diag format
Validating CBOR-Diagnostic format...
[INFO] Root type for validation: schema-csmim.obj.light
[ERROR] Validation from stdin failed:
error validating at cbor location /"resources"/0/"mode": expected value "w" got "wx"
Validation complete

$ ./zValidateData.sh -o csmim.obj.light -f cbor-diag
Starting validation for csmim.obj.light in cbor-diag format
Validating CBOR-Diagnostic format...
[INFO] Root type for validation: schema-csmim.obj.light
[ERROR] Validation from stdin failed:
error validating at cbor location /"resources"/2/"type": expected integer to be in range 0 <= value <= 7, got Integer(8)
Validation complete

$ ./zValidateData.sh -o csmim.obj.light -f cbor-diag
Starting validation for csmim.obj.light in cbor-diag format
Validating CBOR-Diagnostic format...
[INFO] Root type for validation: schema-csmim.obj.light
[ERROR] Validation from stdin failed:
error validating at cbor location /"resources"/2/"type": expected integer to be in range 0 <= value <= 7, got Integer(8)
error validating at cbor location : object missing key: ""subs""
Validation complete

$ ./zValidateData.sh -o csmim.obj.light -f cbor-diag
Starting validation for csmim.obj.light in cbor-diag format
Validating CBOR-Diagnostic format...
[INFO] Root type for validation: schema-csmim.obj.light
[INFO] Validation from stdin is successful
Validation complete
```

## Addressing Existing Comments

1.  **JSON Schema Incompatibilities:** I agree that standard JSON Schema differs significantly from CSMIM's structure (e.g., handling of array items and enums). Adopting JSON Schema would require substantial adaptation of our current YAML/JSON files, which may not be desirable. This approach aims to minimize that.
2.  **Superficially Similar Approach:** Continuing with our existing YAML/JSON structure while adding expressiveness through fields like `unit`, `range`, and `optional` seems like a viable path forward.
3.  **CDDL Advantages:** Unlike JSON Schema, CDDL is designed for CBOR and can describe arbitrary payloads effectively.

By selectively adopting CDDL, we enhance the schema's expressiveness while minimizing changes to our existing structure. This hybrid approach ensures compatibility and ease of adoption.

**Comment by ravishankar-hcltech** [comment]
It's worth noting that the Open Mobile Alliance (**OMA**) Lightweight Machine to Machine (**LwM2M**) specification follows a similar pattern in managing resource constraints. As outlined in their [guidelines](https://github.com/OpenMobileAlliance/lwm2m-registry/wiki/Guidelines#resource-range-or-enumeration), they use:

1. A `Range or Enumeration` field to limit the possible values of a resource.
2. A `Units` field to specify the unit of the resource value.
3. A `Mandatory` field to indicate whether a resource must be instantiated in every instance of an object.

Specifically, their `Mandatory` field serves a similar purpose to our proposed optional field:
- If marked as "Mandatory", the resource MUST be instantiated in any instance of the object it belongs to.
- If marked as "Optional", the resource MAY be omitted from some or all instances of the object.

This similarity highlights a common approach to handling resource constraints, which can inform our own schema design.

**Comment by ravishankar-hcltech** [comment]
## Comparison Summary: ARINC 853 Data Types and Operations

**Data Type** | **YAML-Based Schema Approach** | **CDDL-Based Hybrid Approach**
-- | -- | --
`void` | No value representation. | No value representation.
`raw` | Represented as type: `bytes`. | Represented as `bstr`.<BR>Supports fixed-length constraints via `.size`. <BR>(e.g.,`etag_bytes = bstr .size (1..8)`)
`bool` | Represented as type: `bool`. | Represented as `bool`.
`int`, `uint`, `float` | Use **`minimum`, `maximum`, `exclusive-minimum`, `exclusive-maximum`** for range definition. Supports units via `unit: m/s`. | Compact range expressions like `(0..100)`, `(1/5..8/10/12)` or equality operators (`<`, `<=`, `>`, `>=`) like `uint .lt 50`, `float .le 1047.8`, `uint .gt 0`, and `int .ge 10`. Also supports units via `**unit:** m/s`.
`string` | Use **`min-length`, `max-length`**. <BR>`Regex` validation not natively supported. | Use `.size` for length constraints and `.regexp` for regex validation e.g., <BR>`tstr .size 8`<BR>`tstr .regexp "csmim\\.obj\\.[a-z0-9\\-.]+\\.\\d+"`).
`bytes` | Same as `string`. <BR>Use **`min-length`, `max-length`**.  | Same as `raw` and uses `bstr` type; <BR>Supports fixed-length constraints (e.g., `bstr .size 32`).
`enum` | Use **`enum-values:`** to define `names` and `keys`. | Use compact enumeration syntax like `&(red: 1, green: 2)`, directly aligned with CBOR encoding.
`utc` | No additional constraints defined in YAML. | Represented using CDDL's predefined type `#6.1(int)` or `#6.1(float)` per CBOR tag definitions. (e.g., `#6.1(int) .gt 1741305600  ; represents any date after 2025-03-07`)
| `X[]` (array)  | Use **`min-items`, `max-items`** for array size. Use **`array-items`, `max-length`** for array element constraints. | `[N*M (X)]` - Represents N to M occurrences:<BR>- N defaults to 0 if omitted<BR>- M defaults to ∞ if omitted<BR>- X represents any valid CBOR type.<BR>This can also be combined to include item constraints (e.g., `[1*10 (0..100)]`), representing an array of 1 to 10 elements, each with values between 0 and 100.  |
| `X[][]` (multi dimensional arrays) | Nested YAML structures with repeated use of **`array-items`**.                                                                  | Nested arrays directly represented using `[3*3 [3*3 float  .le 10]]`, supporting constraints at each level.                  |
| `dict`             | Use **`dict-items:`** to define keys, types, and constraints explicitly. Supports **`optional: true`** for keys. Allows unspecified keys for upward compatibility.                                                        | Use CDDL maps (`{ ... }`) to define dictionaries, supporting optional fields (`?`) and wildcard keys (`* tstr => any`) to allow unspecified keys.. |


## Examples: YAML-based vs CDDL-based Schema (side-by-side)

### 1. Basic Types with Constraints

  YAML-based Schema Proposal
  ```yaml
  - id: temperature
    type: int
    minimum: 0
    maximum: 100
    unit: "°C"
  ```
  CDDL-based Hybrid Approach
  
  ```cddl
  - id: temperature
    type: int
    range: "(0..100)"  # CDDL range expression
    unit: "°C"
  ```
  
### 2. Regular Expressions

  YAML-based Schema Proposal
  ```yaml
  - id: email
    type: string
    min-length: 5
    max-length: 255
    # No direct regex support
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: email
    type: string
    range: 'tstr .regexp "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"'
  ```
### 3. Enumerations
  YAML-based Schema Proposal
  ```yaml
  - id: status
    type: enum
    enum-values:
      - name: idle
        key: 0
      - name: active
        key: 1
      - name: error
        key: 2
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: status
    type: enum
    range: "&(idle: 0, active: 1, error: 2)"
  ```
  
### 4. Arrays with Size and Value Constraints
  YAML-based Schema Proposal
  ```yaml
  - id: measurements
    type: uint[]
    min-items: 1
    max-items: 10
    array-items:
      minimum: 0
      maximum: 1000
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: measurements
    type: uint[]
    range: "[1*10 (0..1000)]"  # 1-10 elements, each 0-1000
  ```
### 5. Multi-dimensional Arrays
  YAML-based Schema Proposal
  ```yaml
  - id: matrix
    type: int[][]
    max-items: 3
    array-items:
      max-items: 3
      array-items:
        minimum: 0
        maximum: 100
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: matrix
    type: int[][]
    range: "[*3 [*3 (0..100)]]"  # 3×3 matrix (max), values 0-100
  ```
### 6. Dictionaries with Optional Fields
  YAML-based Schema Proposal
  ```yaml
  - id: settings
    type: dict
    dict-items:
      - key: name
        type: string
      - key: timeout
        type: uint
        default: 30
      - key: retry-count
        type: uint
        maximum: 9
        optional: true
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: settings
    type: dict
    range: "{
      name: tstr,
      timeout: uint .default 30,
      ? retry-count: uint .lt 10  # Optional field
    }"
  ```

### 7. Control Operators (```size```, ```bitwise``` operations)
YAML-based Schema Proposal
```yaml
- id: signature
  type: bytes
  min-length: 32  # Fixed length
  max-length: 32  # Fixed length
 - id: flags
  type: uint
  # No direct equivalent for bitwise operations
  # Bitmask equivalent: 0b00001111 
  # Bits 0-3: read(1), write(2), execute(4), reserved(8)
  minimum: 15
  maximum: 15
```
CDDL-based Hybrid Approach
```cddl
- id: signature
  type: bytes
  range: "bstr .size 32"  # Exactly 32 bytes
  
- id: flags
  type: uint
  range: "bytes .bits 0b00001111"  # Bitwise constraint  [OR]
  range: "(1 / 2 / 4 / 8)" # another way to represent - if only one of the bits are expected to be active
```

### 8. Maps with Wildcard Keys
  YAML-based Schema Proposal
  ```yaml
  - id: translations
    type: dict
    dict-items:
      - key: "*"  # Wildcard for checking presence of any unspecified key? (not explicitly defined)
        type: string
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: translations
    type: dict
    range: "{* tstr => tstr}"  # Any string key to string value
  ```
  
### 9. Complex Nested Structures
  YAML-based Schema Proposal
  ```
  - id: device
    type: dict
    dict-items:
      - key: id
        type: string
      - key: sensors
        type: dict[]
        min-items: 1
        array-items:
          dict-items:
            - key: id
              type: uint
            - key: readings
              type: float[]
            - key: status
              type: enum
              enum-values:
                - name: on
                  key: 1
                - name: off
                  key: 0
  ```
  CDDL-based Hybrid Approach
  ```cddl
  - id: device
    type: dict
    range: "{
      id: tstr,
      sensors: [+ {
        id: uint,
        readings: [* float],
        status: &(on: 1, off: 0)
      }]
    }"
  ```
